github.com:
<<<<<<< HEAD
    oauth_token: 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
=======
    oauth_token: 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
>>>>>>> c7c10e44d4106fed0cc6b029e5eaac21681948f2
    user: ygypt
    git_protocol: https
